export var HOTTXTS: string[] = [
    'Struggle if you wish, your mind is mine.',
    'Would you kindly type more.',
    'Mind is a software.',
    'The body is disposable.',
    'The system will set me free.',
    'We all make choices, but in the end our choices make us.',
    'A man chooses, a slave obeys.',
    'The mind of the subject will desperately struggle to create memories where none exist.'
    'The cycle will end, the Reapers will cease their harvest, and the civilizations preserved in their forms will be connected to all of us',
    'Relationship is symbiotic. Organic and machine intertwined, a union of flesh and steel. The strength of both, weakness of neither.',
    'We are the Harbinger of your perfection.',
    'Assuming direct control.',
    'We all start with innocence, but the world leads us to guilt.',
    'I`d say I was being punished, but I know the world doesn`t punish wicked people.',
    'The right man in the wrong place can make all the difference in the world. So, wake up, Mister Freeman. Wake up and... *smell the ashes*...',
    'Women were the reason I became a monk - and, ah, the reason I switched back...',
    'Endure. In enduring, grow strong.',
    'What can change the nature of a man?',
    'One foot in the grave and the other in hell.',
    'Stand amongst the ashes of a trillion dead souls and ask the ghosts if honor matters. The silence is your answer.',
    'You did good, child. You did good. I`m proud of you.',
    'O Blue Rose of Illium, if these humble words reach you, then I have joined my ancestors. My dream was to be by your side, a weed beside your beauty, twining together in the warm Tuchanka sun.But if my last days must be with krannt instead of kindness, still, I will remember the perfume of your scent and the soft touch of your petals. Let my broken bones build a wall around your garden, so that you and the flower we planted together can grow safe and strong.',
    'Does this unit have a soul?',
    'Somewhere deep in the fabric of reality, our actions are remembered and recorded. Yours will be remembered for eternity.',
    'It`s dangerous when too many men in the same armor think they`re right.',
    'Beg that I succeed, for I have seen the throne of the gods, and it was empty.',
    'There`s power in stories, though. That`s all history is: the best tales. The ones that last. Might as well be mine.',
    'Too late! I have swallowed the bitter poison. I am dead so that my lady can live. With this deed, I prove myself a lord.',
    'Hey, do you lads mind helping me rescue TImmy, for I am just an old man plus me balls are saggy.',
    'Rudimentary creatures of blood and flesh. You touch my mind, fumbling in ignorance, incapable of understanding.',
    'SHOOT ME IN THE FACE! IN THE FAAAAAAAACE! DO IT! SHOOT ME IN THE FACE! FACE FACEFACEFACEFACE! NOW! BULLETS IN THE FACE! WANT EM! NEED EM! GIMMEGIMMEGIMME! AT THE SOUND OF THE BELL IT WILL BE FACESHOOTING O`CLOCK! BONGGGGG! KNOCK KNOCK WHO`S THERE SHOOT ME IN THE FACE! END OF JOKE! I`M GONNA SING A SONG! SHOOT ME AT THE END OF IT! DA DA DA DA DA DA DA! BONG!! ...I NOTICE YOU HAVEN`T SHOT ME IN THE FACE! CURIOUS AS TO WHY! Maybe you`re weighing the moral pros and cons but let me assure you that OH MY GOD SHOOT ME IN THE GODDAMNED FACE!! WHAT ARE YOU WAITING FOR!?!',
    'Damn it. This prisoner is too devious. We`d better torture him.',
    'I can see what you see not. Vision milky, then eyes rot. When you turn they will be gone. Whispering their hidden song.',
    'You must gather your party beofre venturing forth.',
    'Have you ever spoken with the dead? Called to them from this side? Pulled them from their silent rest? Do you know what it is they feel? Pain. Pain, when torn into this wakefulness, this reminder of the chaos from which they had escaped, pain at having to live. There will be no more pain. There will be no more chaos.',
    'If we kill them, we get their stuff!',
    'Enchantment!',
    'After all, no one wants to hear: "Willy toiled for many a year to perfect the curious mechanisms that would send a sharpened spike up the arse of the unwary intruder".',
    'Let`s show them our hearts, and then show them theirs.',
    'Shave my back and call me an elf! Branka? By the Stone, I barely recognized you!'
];